### ISSUE TITLE
Stuart - download of PDF

### ISSUE THREAD

**Issue by Stuartmeyer** [kigster/laser-cutter#11]
Hi

Tried to follow instructions on reinventone page but does not do anything. Re-tried the program but still does not download the PDF, just hangs

Stuart

**Comment by kigster** [comment]
You may have supplied numbers that take too long to generate.

To fix this — 1) please do NOT supply TAB width (at least initially, to see if it generates PDF without it), 2) provide tab width but make it rather large, so that you only have 5-10 tabs per side. 

Usually it hangs when the number of tabs per side you are generating is in 100s.

**Comment by Stuartmeyer** [comment]
Hi Konstantin


Nope, none of your options provided worked, still just hangs.

I have used your box program any times it is just in the last week that it is giving this problem.


Kind Regards

Stuart Meyer
HR and Administration Manager
Toyota Tsusho South Africa Processing (TTSAP)
Tel: 031 9494528
Fax: 0865009742 / 031 9021438
Cell: 0836338293

**Comment by kigster** [comment]
Can you please provide exact dimensions of what you are trying to generate? 

You can take a screenshot and attach here.

**Comment by Stuartmeyer** [comment]
So this is the start page
[cid:image005.jpg@01D2DEB0.0C76FA60]
I enter the specs
[cid:image006.jpg@01D2DEB0.0C76FA60]
Click on download PDF and nothing happens just goes back to the above page.

Even when I click on the help buttons the “?” nothing happens

I can try enter a tab width or leave blank for automatic selection the result is the same - nothing

I then try the same thing in millimeters and nothing.


Kind Regards

Stuart Meyer
HR and Administration Manager
Toyota Tsusho South Africa Processing (TTSAP)
Tel: 031 9494528
Fax: 0865009742 / 031 9021438
Cell: 0836338293

**Comment by kigster** [comment]
@Stuartmeyer What browser are you using? None of your screenshots went through, because you probably need to attach them to the ticket by going here: https://github.com/kigster/laser-cutter/issues/11

Now, if nothing happens when you click on (?) that means something is broken with the javascript. This can happen if you are using an old Internet Explorer (for example). If this is the case, your solution is to install Google Chrome, and use that instead.  You can also use Safari for Mac or Windows, both work with the website.

**Comment by Stuartmeyer** [comment]
I  will try on my home computer we are not allowed Chrome at work.

We are using IE version 11 (latest)

AS I said previously I have used your program many times using same internet  it is just suddenly in the last 2 weeks it stopped.

Kind Regards

Stuart Meyer
HR and Administration Manager
Toyota Tsusho South Africa Processing (TTSAP)
Tel: 031 9494528
Fax: 0865009742 / 031 9021438
Cell: 0836338293

**Comment by kigster** [comment]
OK, you are correct, makeabox was not working with Internet Explorer on Windows.

It should now be fixed.

Thanks for reporting it!
K

**Comment by Stuartmeyer** [comment]
Thank you  I will check later today

Kind Regards

Stuart Meyer
HR and Administration Manager
Toyota Tsusho South Africa Processing (TTSAP)
Tel: 031 9494528
Fax: 0865009742 / 031 9021438
Cell: 0836338293
